version: '3.9'

services:
    smart-summary-backend:
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        container_name: smart-summary-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3002:3001
        restart: always
