version: '3.9'

services:
    smart-summary-backend:
        container_name: smart-summary-backend
        build:
            context: .
            dockerfile: Dockerfile
       # environment:
           # - SESSION_SECRET=${SESSION_SECRET}
           # - MONGODB_URI=${MONGODB_URI}
           # - CLIENT_ID=${CLIENT_ID}
           # - CLIENT_SECRET=${CLIENT_SECRET}
           # - TENANT_ID=${TENANT_ID}
        ports:
            - 3002:3001
        restart: always
