version: '3.9'

services:
    smart-summary-backend:
        container_name: smart-summary-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3002:3001
        restart: always
